add-htmlcssfile
josuerushanika/Portfolio-finish-mobile-version pull request #1
Opened 2022-12-03 12:43 UTC by josuerushanika

2022-12-03 13:08 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @josuerushanika 👋 , 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 13:08 UTC, abdulhamiid commented on index.html
> +    </article>
Your design 👇 
![image](https://user-images.githubusercontent.com/78251927/205442135-51e8d921-3b64-4f5c-91af-0793aa77d4c6.png)

Figma design 👇 
![image](https://user-images.githubusercontent.com/78251927/205442208-1b60f908-bfdd-42cd-9da3-669facb89fba.png)

- [ ] Please kindly use the same font as [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) in this section as mentioned in the[ project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md).

2022-12-03 17:17 UTC, Tadesse-Alemayehu approved these changes
### Hi @josuerushanika 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![68747470733a2f2f6669636f666f72756d732e6d796669636f2e636f6d2f74352f696d6167652f736572766572706167652f696d6167652d69642f343932363069463839303835363833444139334135422f696d6167652d73697](https://user-images.githubusercontent.com/69077061/200411711-6e741427-6e46-4354-932f-f1445ecc09bd.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. 🙏
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  Good commit history 🥇
 - [ ]  Good PR title/description 💯
 - [ ]  All linters passed 🥇
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 07:22 UTC, cindykandie commented on index.html
> +            <li class="social-icon twitter">
Good use of HTML Semantics Keep up😎

2022-12-08 07:22 UTC, huzaifakhan0308 commented on .github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
I think all the things were already good so there is no need for more changes💥💫▶️▶️😎

2022-12-13 14:39 UTC, merged